
- name: Install and Configure Filebeat
  hosts: all
  connection: local

  roles:
    - role: filebeat
      when: ansible_os_family == 'Debian'
#    become: yes
#    vars:
#      user_name: rancher_user
